### ISSUE TITLE
Could not find a version that satisfies the requirement acme

### ISSUE THREAD

**Issue by notaduck** [letsencrypt/letsencrypt-debian#11]
I am having a issue when i am trying to setup Letsencrypt on a Ubuntu 14.04 LTS Based system with Nginx. 

    daniel@rproxy:~/letsencrypt$ ./venv/bin/pip install -r requirements.txt .
    Unpacking /home/daniel/letsencrypt
      Running setup.py (path:/tmp/pip-rorTj0-build/setup.py) egg_info for package from file:///home/daniel/letsencrypt
       
    Downloading/unpacking ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6 (from -r requirements.txt (line 2))
      Cloning https://github.com/kuba/ConfigArgParse.git (to python2.6) to ./venv/build/ConfigArgParse
      Running setup.py (path:/home/daniel/letsencrypt/venv/build/ConfigArgParse/setup.py) egg_info for package ConfigArgParse
       
    Downloading/unpacking acme==0.1.0.dev0 (from letsencrypt==0.1.0.dev0)
      Could not find a version that satisfies the requirement acme==0.1.0.dev0 (from letsencrypt==0.1.0.dev0) (from versions: 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024, 0.0.0.dev20151006, 0.0.0.dev20151008, 0.0.0.dev20151017, 0.0.0.dev20151020, 0.0.0.dev20151021, 0.0.0.dev20151024)
    Cleaning up...
    No distributions matching the version for acme==0.1.0.dev0 (from letsencrypt==0.1.0.dev0)
    Storing debug log for failure in /home/daniel/.pip/pip.log

**Comment by waja** [comment]
you should have a look into https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774387#25

**Comment by fmarier** [comment]
Sorry, this repository is for the packaging of letsencrypt for Debian. I suggest you ask for help on the mailing list where you're more likely to find people who can help: https://groups.google.com/a/letsencrypt.org/forum/#!forum/client-dev
