### ISSUE TITLE
Re-enable the letsencrypt upstream tests

### ISSUE THREAD

**Issue by fmarier** [letsencrypt/letsencrypt-debian#4]
To get the package to build, I [disabled](https://github.com/letsencrypt/letsencrypt-debian/blob/master/debian/rules#L36-L37) some of the upstream tests.

We used to work-around test failures but [that patch](https://github.com/letsencrypt/letsencrypt-debian/blob/master/debian/patches/revert-pr-622.patch) no longer applies cleanly, so I've [disabled it](https://github.com/letsencrypt/letsencrypt-debian/blob/master/debian/patches/series#L3) for now.

We should either fix the patch or (ideally) get a proper [upstream fix](https://github.com/letsencrypt/letsencrypt/issues/779) so that we can start running the tests again.

**Comment by fmarier** [comment]
Thanks for fixing this @hlieberman.

BTW, I think we should take advantage of the review interface in GitHub to submit our changes via the PR system and review each other's changes. Your last commits looked all good to me.

**Comment by hlieberman** [comment]
Definitely. Will do!
