### ISSUE TITLE
keep Debian packaging only in this branch

### ISSUE THREAD

**Issue by chadmiller** [letsencrypt/letsencrypt-debian#8]
I don't think we need to have the "upstream" code in this branch. It can only be stale. 

All we need track is the debian/ dir, and refer to upstream releases in the debian/changelog and implement a "get-packaged-orig-source" rule in debian/rules that checks out the correct version from Github.

**Comment by fmarier** [comment]
We'll keep the upstream code (in the `upstream` branch) tied to the last tarball that we imported. That's standard workflow with `git-buildpackage`.

I do agree that it's confusing at the moment because upstream hasn't yet done their first tarball release, but it's coming soon :)
